### ISSUE TITLE
Profile tab is not showing

### ISSUE THREAD

**Issue by ThiagoMiranda** [felixge/node-memory-leak-tutorial#4]
Hi!!
I'm having some memory issues in a nodeJS application that is currently on production so I'm trying to search for a way to detect and prevent it.. I came across this tutorial but when I open the debug page the profile tab is not showing ( after I've followed the steps from the tutorial ). Am I doing something wrong?

Thanks!

**Comment by vicapow** [comment]
+1

**Comment by ecdeveloper** [comment]
The same issue - http://s3.kkloud.com/gett/6jylO3L/Screenshot-2.png.0x675.x0h3a1e8nu680k9qvgz0rwjacwka9k9.png
Does anybody solved that?

**Comment by minchenkov** [comment]
+1

**Comment by szayat** [comment]
same here

**Comment by wangbus** [comment]
Same here.

**Comment by dcolens** [comment]
as per https://github.com/dannycoates/node-inspector/issues/126, try downgrading to 0.1.10 it worked for me!

**Comment by muffik** [comment]
how downgrade it to 0.1.10??

**Comment by funston** [comment]
npm install -g node-inspector@0.1.10

**Comment by NachoSoto** [comment]
No luck for me either. It's really sad that this repo is no longer maintained.

**Comment by felixge** [comment]
> No luck for me either. It's really sad that this repo is no longer maintained.

Good point! Since you guys seem interested, I just made all of you contributors on the project:

@NachoSoto @rschiavi @muffik @dcolens @wangbus @szayat @minchenkov @ecdeveloper @vicapow @ThiagoMiranda : If any of you has figured out how to get things to work again - please share it by updating the readme.

:heart:

**Comment by vicapow** [comment]
Hey, sorry Felixge. I know a "+1" isn't very helpful. when it comes to open source, it's way easier to ask for features, or report bugs, then it is to actually contribute or simply say "thank you." I can't say I really have the domain knowledge to work on this issue but I am trying to do what I can to give back more to the community I've taken so much from.

\- Apologies, & Thank you

**Comment by felixge** [comment]
@vicapow np, I just added everybody to the repo as I won't have time to help with this myself anytime soon.

**Comment by bnitica** [comment]
npm install -g node-inspector@0.1.10 worked for me.
1. I stopped both processes node-inspector and "node --debug leak.js"
2. npm install -g node-inspector@0.1.10
3. execute "node --debug leak.js" and node-inspector
4. refresh the Chrome tab with the debugger address

**Comment by palominoz** [comment]
`npm install -g node-inspector@0.1.10` worked for me too :+1:

**Comment by tlhunter** [comment]
I've installed node-inspector 0.1.10, however once I click that little eye ball icon, the inspector crashes:

```
/usr/local/lib/node_modules/node-inspector/lib/session.js:910
              head: JSON.parse(msg.body.value)
                                       ^
TypeError: Cannot read property 'value' of undefined
    at /usr/local/lib/node_modules/node-inspector/lib/session.js:910:40
    at Object.create.processResponse.value (/usr/local/lib/node_modules/node-inspector/lib/callback.js:22:18)
    at parse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:38:29)
    at parse (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:65:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/node-inspector/lib/debugger.js:114:5)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
```

**Comment by jaromirmuller** [comment]
I have same problem @tlhunter

**Comment by warrenpoon** [comment]
I have this same problem, I am running Node v0.11.13, node-inspector 0.1.10:
<code>
node-inspector app.js 
   info  - socket.io started
visit http://0.0.0.0:8080/debug?port=5858 to start debugging
/usr/local/lib/node_modules/node-inspector/lib/session.js:910
              head: JSON.parse(msg.body.value)
                                       ^
</code>

**Comment by sean-hill** [comment]
I have same problem @tlhunter

**Comment by johnsmith0209** [comment]
Hi! Is there any one still working on this? I have the same problem @tlhunter and I looked into 'msg' found there is an error msg and couldn't find body here 

``` javascript
{ seq: 22,
  request_seq: 8,
  type: 'response',
  command: 'evaluate',
  success: false,
  message: 'TypeError: Object #<Snapshot> has no method \'stringify\'',
  running: true }
```

**Comment by bhuvanark** [comment]
Hi!
I have same problem. Could someone help?

/node_modules/node-inspector/lib/session.js:910
              head: JSON.parse(msg.body.value)
                                       ^
TypeError: Cannot read property 'value' of undefined
    at /node_modules/node-inspector/lib/session.js:910:40
    at Object.create.processResponse.value (/node_modules/node-inspector/lib/cal
lback.js:22:18)
    at parse (/node_modules/node-inspector/lib/debugger.js:38:29)
    at parse (/node_modules/node-inspector/lib/debugger.js:65:7)
    at Socket.<anonymous> (/node_modules/node-inspector/lib/debugger.js:114:5)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

Thanks in advance.

**Comment by bhuvanark** [comment]
Hi All,
Checking for msg.body.value existence in session.js of node-inspector, solved problem of node-inspector crash.

Code Snippet:
if(msg.body && msg.body.value) {
            sendResponse(seq, true, {
              profile: {
                title: 'org.webkit.profiles.user-initiated.' + uid,
                uid: uid,
                typeId: type,
                head: JSON.parse(msg.body.value)
              }
            });
          }

But v8-profiler, takeSnapshot values are not displayed in profiler.
Thanks.
